# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Python39
                                 A QGIS plugin
 this plugin allows to perform various geodetic calculations related to height, area, coordinates
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-02
        copyright            : (C) 2024 by Paula Domarecka, Emilia Brytan
        email                : 01179125@pw.edu.pl, 01179109@pw.edu.pl
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Python39 class from file Python39.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geo_calc import Python39
    return Python39(iface)
